sh generate_web.sh bur  ../../BURScan/2020/
sh generate_web.sh inm  ../../INMScan/2020/
sh generate_web.sh mwe  ../../MWEScan/2020/
sh generate_web.sh pwg  ../../PWGScan/2020/
sh generate_web.sh skd  ../../SKDScan/2020/
sh generate_web.sh stc  ../../STCScan/2020/
sh generate_web.sh vcp  ../../VCPScan/2020/
sh generate_web.sh acc  ../../ACCScan/2020/
sh generate_web.sh ae  ../../AEScan/2020/
sh generate_web.sh ap90  ../../AP90Scan/2020/
sh generate_web.sh ap  ../../APScan/2020/
sh generate_web.sh ben  ../../BENScan/2020/
sh generate_web.sh bhs  ../../BHSScan/2020/
sh generate_web.sh bop  ../../BOPScan/2020/
sh generate_web.sh bor  ../../BORScan/2020/
sh generate_web.sh cae  ../../CAEScan/2020/
sh generate_web.sh ccs  ../../CCSScan/2020/
sh generate_web.sh gra  ../../GRAScan/2020/
sh generate_web.sh gst  ../../GSTScan/2020/
sh generate_web.sh ieg  ../../IEGScan/2020/
sh generate_web.sh krm  ../../KRMScan/2020/
sh generate_web.sh mci  ../../MCIScan/2020/
sh generate_web.sh md  ../../MDScan/2020/
sh generate_web.sh mw72  ../../MW72Scan/2020/
sh generate_web.sh mw  ../../MWScan/2020/
sh generate_web.sh pd  ../../PDScan/2020/
sh generate_web.sh pe  ../../PEScan/2020/
sh generate_web.sh pgn  ../../PGNScan/2020/
sh generate_web.sh pui  ../../PUIScan/2020/
sh generate_web.sh pw  ../../PWScan/2020/
sh generate_web.sh sch  ../../SCHScan/2020/
sh generate_web.sh shs  ../../SHSScan/2020/
sh generate_web.sh snp  ../../SNPScan/2020/
sh generate_web.sh vei  ../../VEIScan/2020/
sh generate_web.sh wil  ../../WILScan/2020/
sh generate_web.sh yat  ../../YATScan/2020/
sh generate_web.sh pwkvn  ../../PWKVNScan/2020/
sh generate_web.sh lan  ../../LANScan/2020/
sh generate_web.sh armh  ../../ARMHScan/2020/
sh generate_web.sh lrv  ../../LRVScan/2022/
