sh generate_web.sh bur  ../../bur
sh generate_web.sh inm  ../../inm
sh generate_web.sh mwe  ../../mwe
sh generate_web.sh pwg  ../../pwg
sh generate_web.sh skd  ../../skd
sh generate_web.sh stc  ../../stc
sh generate_web.sh vcp  ../../vcp
sh generate_web.sh acc  ../../acc
sh generate_web.sh ae  ../../ae
sh generate_web.sh ap90  ../../ap90
sh generate_web.sh ben  ../../ben
sh generate_web.sh bhs  ../../bhs
sh generate_web.sh bop  ../../bop
sh generate_web.sh bor  ../../bor
sh generate_web.sh cae  ../../cae
sh generate_web.sh ccs  ../../ccs
sh generate_web.sh gra  ../../gra
sh generate_web.sh gst  ../../gst
sh generate_web.sh ieg  ../../ieg
sh generate_web.sh krm  ../../krm
sh generate_web.sh mci  ../../mci
sh generate_web.sh md  ../../md
sh generate_web.sh mw72  ../../mw72
sh generate_web.sh mw  ../../mw
sh generate_web.sh pe  ../../pe
sh generate_web.sh pgn  ../../pgn
sh generate_web.sh pui  ../../pui
sh generate_web.sh pw  ../../pw
sh generate_web.sh sch  ../../sch
sh generate_web.sh shs  ../../shs
sh generate_web.sh snp  ../../snp
sh generate_web.sh vei  ../../vei
sh generate_web.sh wil  ../../wil
sh generate_web.sh yat  ../../yat
sh generate_web.sh lan  ../../lan
sh generate_web.sh pwkvn  ../../pwkvn
sh generate_web.sh armh  ../../armh
sh generate_web.sh lrv  ../../lrv
sh generate_web.sh abch  ../../abch


