rm -r pdfpages
mkdir pdfpages
cp 'archive_pages/archive 135.pdf' pdfpages/f01.pdf
cp 'archive_pages/archive 136.pdf' pdfpages/f02.pdf
cp 'archive_pages/archive 137.pdf' pdfpages/f03.pdf
cp 'archive_pages/archive 138.pdf' pdfpages/f04.pdf
cp 'archive_pages/archive 139.pdf' pdfpages/f05.pdf
cp 'archive_pages/archive 140.pdf' pdfpages/f06.pdf
cp 'archive_pages/archive 141.pdf' pdfpages/f07.pdf
cp 'archive_pages/archive 142.pdf' pdfpages/f08.pdf
cp 'archive_pages/archive 143.pdf' pdfpages/f09.pdf
cp 'archive_pages/archive 144.pdf' pdfpages/f10.pdf
cp 'archive_pages/archive 145.pdf' pdfpages/f11.pdf
cp 'archive_pages/archive 146.pdf' pdfpages/f12.pdf
cp 'archive_pages/archive 147.pdf' pdfpages/f13.pdf
cp 'archive_pages/archive 148.pdf' pdfpages/f14.pdf
cp 'archive_pages/archive 149.pdf' pdfpages/pg05.pdf
cp 'archive_pages/archive 150.pdf' pdfpages/pg06.pdf
cp 'archive_pages/archive 151.pdf' pdfpages/pg07.pdf
cp 'archive_pages/archive 152.pdf' pdfpages/pg08.pdf
cp 'archive_pages/archive 153.pdf' pdfpages/pg09.pdf
cp 'archive_pages/archive 154.pdf' pdfpages/pg10.pdf
cp 'archive_pages/archive 155.pdf' pdfpages/pg11.pdf
cp 'archive_pages/archive 156.pdf' pdfpages/pg12.pdf
cp 'archive_pages/archive 157.pdf' pdfpages/pg13.pdf
cp 'archive_pages/archive 158.pdf' pdfpages/pg14.pdf
cp 'archive_pages/archive 159.pdf' pdfpages/pg15.pdf
cp 'archive_pages/archive 160.pdf' pdfpages/pg16.pdf
cp 'archive_pages/archive 161.pdf' pdfpages/pg17.pdf
cp 'archive_pages/archive 162.pdf' pdfpages/pg18.pdf
cp 'archive_pages/archive 163.pdf' pdfpages/pg19.pdf
cp 'archive_pages/archive 164.pdf' pdfpages/pg20.pdf
cp 'archive_pages/archive 165.pdf' pdfpages/pg21.pdf
cp 'archive_pages/archive 166.pdf' pdfpages/pg22.pdf
cp 'archive_pages/archive 167.pdf' pdfpages/pg23.pdf
cp 'archive_pages/archive 168.pdf' pdfpages/pg24.pdf
cp 'archive_pages/archive 169.pdf' pdfpages/pg25.pdf
cp 'archive_pages/archive 170.pdf' pdfpages/pg26.pdf
cp 'archive_pages/archive 171.pdf' pdfpages/pg27.pdf
cp 'archive_pages/archive 172.pdf' pdfpages/pg28.pdf
cp 'archive_pages/archive 173.pdf' pdfpages/pg29.pdf
cp 'archive_pages/archive 174.pdf' pdfpages/pg30.pdf
cp 'archive_pages/archive 175.pdf' pdfpages/pg31.pdf
cp 'archive_pages/archive 176.pdf' pdfpages/pg32.pdf
cp 'archive_pages/archive 177.pdf' pdfpages/pg33.pdf
cp 'archive_pages/archive 178.pdf' pdfpages/pg34.pdf
cp 'archive_pages/archive 179.pdf' pdfpages/pg35.pdf
cp 'archive_pages/archive 180.pdf' pdfpages/pg36.pdf
cp 'archive_pages/archive 181.pdf' pdfpages/pg37.pdf
cp 'archive_pages/archive 182.pdf' pdfpages/pg38.pdf
cp 'archive_pages/archive 183.pdf' pdfpages/pg39.pdf
cp 'archive_pages/archive 184.pdf' pdfpages/pg40.pdf
cp 'archive_pages/archive 185.pdf' pdfpages/pg41.pdf
cp 'archive_pages/archive 186.pdf' pdfpages/pg42.pdf
cp 'archive_pages/archive 187.pdf' pdfpages/pg43.pdf
cp 'archive_pages/archive 188.pdf' pdfpages/pg44.pdf
cp 'archive_pages/archive 189.pdf' pdfpages/pg45.pdf
cp 'archive_pages/archive 190.pdf' pdfpages/pg46.pdf
cp 'archive_pages/archive 191.pdf' pdfpages/pg47.pdf
cp 'archive_pages/archive 192.pdf' pdfpages/pg48.pdf
cp 'archive_pages/archive 193.pdf' pdfpages/pg49.pdf
cp 'archive_pages/archive 194.pdf' pdfpages/pg50.pdf
cp 'archive_pages/archive 195.pdf' pdfpages/pg51.pdf
cp 'archive_pages/archive 196.pdf' pdfpages/pg52.pdf
cp 'archive_pages/archive 197.pdf' pdfpages/pg53.pdf
cp 'archive_pages/archive 198.pdf' pdfpages/pg54.pdf
cp 'archive_pages/archive 199.pdf' pdfpages/pg55.pdf
cp 'archive_pages/archive 200.pdf' pdfpages/pg56.pdf
cp 'archive_pages/archive 201.pdf' pdfpages/pg57.pdf
cp 'archive_pages/archive 202.pdf' pdfpages/pg58.pdf
echo "copy 68 files from archive_pages to pdfpages"
